# The s-step GMRES algorithm

MATLAB implementations of s-step GMRES with classical or modfied Arnoldi
process.
The Krylov basis can be chosen to be generated by monomial, Newton, and
Chebyshev polynomials with or without scaling.

## Related publications
* Carson, E., & Ma, Y. (2024). [On the backward stability of s-step GMRES].


## Included MATLAB files
### Source code
* **_gmres_sstep.m_** is an implementation of the restarted s-step GMERS
(also called communication-avoiding GMRES) with the classical Arnoldi process.
* **_gmres_sstep_norestart.m_** is an implementation of the no restarted
s-step GMERS (also called communication-avoiding GMRES) with the classical
Arnoldi process.
* **_gmres_sstep_modified.m_** is an implementation of the no restarted
s-step GMERS (also called communication-avoiding GMRES) with the modified
Arnoldi process.
* **_computeBasis.m_** computes an s-dimensional Krylov subspace basis
using the specified matrix, vector, and polynomial coefficients.
This file is copied from https://github.com/eccarson/mixedsstep.git.
* **_basisparams.m_** computes the polynomial basis coefficients used in
the computeBasis function (options are monomial, Newton, or Chebyshev
polynomials).
This file is copied from https://github.com/eccarson/mixedsstep.git.
* **_lejapoints.m_** computes a set of leja points of specified size within
a specified interval; used for computing the Newton basis coefficients.
This file is copied from https://github.com/eccarson/mixedsstep.git.
### Test code
* **_test_sstep_gmres.m_** is to compare s-step GMRES with the classical
Arnoldi process and the modified Arnoldi process for three test matrices:
494_bus, fs_183_6, and sherman2.
* **_bad_example.m_** is an example to show the instability of s-step GMRES 
with the classical Arnoldi process.
* **_draw_sstep_backwarderr.m_** is to plot the backward error of s-step
GMRES with the classical and modified Arnoldi process using three typical
block size s = 1, 4, 16, for testing three matrices: 494_bus, fs_183_6, and
sherman2.




